### ISSUE TITLE
Upgrading from 0.16.1 to 0.17.x causes vite build error

### ISSUE THREAD

**Issue by kefahi** [josdejong/svelte-jsoneditor#264]
Hello,

On my project, yarn build (using vite 4.3.x) is woking just fine with 0.16.1.
Once I upgraded to 0.17.0 and 0.17.1 I get the following build error 

```
yarn build
yarn run v1.22.19
$ vite build
vite v4.3.1 building for production...
[Routify 3] build triggered by initial (111 ms)
✓ 31 modules transformed.
✓ built in 2.61s
[commonjs--resolver] Missing "./components/JSONEditor.svelte" specifier in "svelte-jsoneditor" package
error during build:
Error: Missing "./components/JSONEditor.svelte" specifier in "svelte-jsoneditor" package
    at e (file:///home/kefah/Development/edraj/frontend-skeleton/node_modules/vite/dist/node/chunks/dep-24daf00c.js:16638:25)
    at n (file:///home/kefah/Development/edraj/frontend-skeleton/node_modules/vite/dist/node/chunks/dep-24daf00c.js:16638:627)
    at o (file:///home/kefah/Development/edraj/frontend-skeleton/node_modules/vite/dist/node/chunks/dep-24daf00c.js:16638:1297)
    at resolveExportsOrImports (file:///home/kefah/Development/edraj/frontend-skeleton/node_modules/vite/dist/node/chunks/dep-24daf00c.js:23396:20)
    at resolveDeepImport (file:///home/kefah/Development/edraj/frontend-skeleton/node_modules/vite/dist/node/chunks/dep-24daf00c.js:23415:31)
    at tryNodeResolve (file:///home/kefah/Development/edraj/frontend-skeleton/node_modules/vite/dist/node/chunks/dep-24daf00c.js:23104:20)
    at Object.resolveId (file:///home/kefah/Development/edraj/frontend-skeleton/node_modules/vite/dist/node/chunks/dep-24daf00c.js:22865:28)
    at file:///home/kefah/Development/edraj/frontend-skeleton/node_modules/rollup/dist/es/shared/node-entry.js:24526:40
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async PluginDriver.hookFirstAndGetPlugin (file:///home/kefah/Development/edraj/frontend-skeleton/node_modules/rollup/dist/es/shared/node-entry.js:24426:28)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

I tried adding the following to vite.config.js without avail

```
  optimizeDeps: {
    include: [
      'svelte-jsoneditor',
      'json-source-map',
      'classnames',
      'natural-compare-lite',
      'ajv-dist',
      'immutable-json-patch',
      'lodash-es',
      '@fortawesome/free-regular-svg-icons',
      'jmespath'
    ]
  },
```

**Comment by kefahi** [comment]
This was due to improper import from my side. I was importing the inner components instead of importing from svelte-jsoneditor directly.

**Comment by josdejong** [comment]
Good to hear you got it working. Version 0.17.0 is more strict and only exports the main entry file.
