### ISSUE TITLE
Table mode: columns resizing due to flex display

### ISSUE THREAD

**Issue by echan00** [josdejong/svelte-jsoneditor#421]
During table mode, I've noticed if the amount of data in a column varies a lot in size, the table columns will resize as you scroll up/down making it difficult to follow the table and contents. 

I've hacked this with `.jse-modal-contents{ display: block !important; }` which works, but causes in an error in development:

```
ResizeObserver loop completed with undelivered notifications.
    at handleError (webpack-internal:///./node_modules/webpack-dev-server/client/overlay.js:252:58)
    at eval (webpack-internal:///./node_modules/webpack-dev-server/client/overlay.js:271:7)
```

I would appreciate any pointers to best resolve this!

**Comment by josdejong** [comment]
Thanks for reporting. Can you give an example that demonstrates the issue?

**Comment by echan00** [comment]
Here is a quick video, you can see as I scroll down the table the columns widths are resizing based on the view. This can make it difficult to follow the table if each column is shortening/expanding as you review the data.

https://github.com/josdejong/svelte-jsoneditor/assets/6287299/d31cdc41-fc68-410b-8fd1-43a13512c259

**Comment by josdejong** [comment]
Thanks. How can I reproduce this? Can you share a JSON document?

**Comment by echan00** [comment]
of course [test.json](https://github.com/josdejong/svelte-jsoneditor/files/14792876/test.json)

**Comment by josdejong** [comment]
> I believe this is the default for any html table and in MS excel.

😂 I think you're right. And this is one of my annoyances with Excel: after opening a file you first have to manually adjust the widths of the columns. I hope with `svelte-jsoneditor` we can do better.

Opening with a default width and allowing to change the width is an option indeed. Maybe set the initial width based on the initially visible items. That would be a good guess in most cases. And then the editor should not change it automatically when scrolling. We could create a button "Fit" to resize all columns again to fit the currently visible contents or something like that.

**Comment by echan00** [comment]
Agree with your comments. I think it also depends on the user's window/monitor size. If the size is too small the current setting will probably be very difficult. 

I believe most people who use jsoneditor in table mode are reviewing/revising lots of data, a "Fit" button to resize would be great for a "pro" user who can take advantage. It depends who you want to serve here, the pro user or the average one who is likely not away of all the existing features.

**Comment by echan00** [comment]
I can't promise I'll be able to help, but I'll take a look if you think a button to switch is the way to go

**Comment by josdejong** [comment]
Thanks! 

My thoughts right now: 

A solution that doesn't require a manual action still has my preference, though I'm not sure whehter that will work out. So first I would like to experiment a bit to see whether my idea of a smooth transition or adjusting the horizontal scroll could work ([idea 1 and 2 here](https://github.com/josdejong/svelte-jsoneditor/issues/421#issuecomment-2033962112)). If those experiments are no success, the second best option is to initially auto fit and lock the widths, and create a button to call fit and lock again. Does that make sense?

**Comment by echan00** [comment]
Sure let me know if I can help you test anything 👍
