### ISSUE TITLE
TransformWizard.svelte is missing tbody tag inside table

### ISSUE THREAD

**Issue by mantulen** [josdejong/svelte-jsoneditor#485]
There is a breaking change in Svelte 5 that requires `<tbody>` tag in between `<table>` and `<tr>` or the below build error is raised, more info here:

https://github.com/sveltejs/svelte/issues/9785

```
✘ [ERROR] node_modules/svelte-jsoneditor/components/modals/TransformWizard.svelte:94:2 `<tr>` is invalid inside `<table>` [plugin vite-plugin-svelte:optimize-svelte]

    node_modules/svelte-jsoneditor/components/modals/TransformWizard.svelte:94:2:
      94 │  <tr>
         ╵   ^

  The plugin "vite-plugin-svelte:optimize-svelte" was triggered by this import

    node_modules/svelte-jsoneditor/components/modals/TransformModal.svelte:21:28:
      21 │ import TransformWizard from './TransformWizard.svelte';
         ╵                             ~~~~~~~~~~~~~~~~~~~~~~~~~~

4:35:53 AM [vite] error while updating dependencies:
Error: Build failed with 1 error:
node_modules/svelte-jsoneditor/components/modals/TransformWizard.svelte:94:2: ERROR: [plugin: vite-plugin-svelte:optimize-svelte] node_modules/svelte-jsoneditor/components/modals/TransformWizard.svelte:94:2 `<tr>` is invalid inside `<table>`
    at failureErrorWithLog (/workspaces/cts-portal/src/frontend/node_modules/vite/node_modules/esbuild/lib/main.js:1472:15)
    at /workspaces/cts-portal/src/frontend/node_modules/vite/node_modules/esbuild/lib/main.js:945:25
    at /workspaces/cts-portal/src/frontend/node_modules/vite/node_modules/esbuild/lib/main.js:1353:9
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
```

**Comment by mantulen** [comment]
Closing this as I see it is being addressed in the Svelte 5 PR:

https://github.com/josdejong/svelte-jsoneditor/pull/476

**Comment by josdejong** [comment]
Yeah, there are quite some issues upgrading to Svelte 5 though, we're not there yet 😅 .
